"""empty message

Revision ID: 1675887d5bf3
Revises: 6ccf6c0b8aae
Create Date: 2022-01-14 17:42:31.705095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1675887d5bf3'
down_revision = '6ccf6c0b8aae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('state_fullname', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'state_fullname')
    # ### end Alembic commands ###
