"""empty message

Revision ID: 978c821cfda3
Revises: 
Create Date: 2022-01-14 15:50:33.145087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '978c821cfda3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('first_name', sa.String(length=40), nullable=False),
    sa.Column('middle_name', sa.String(length=40), nullable=True),
    sa.Column('last_name', sa.String(length=40), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=40), nullable=False),
    sa.Column('country', sa.String(length=40), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('latitud', sa.Float(precision=20), nullable=False),
    sa.Column('longitud', sa.Float(precision=20), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('city')
    op.drop_table('user')
    # ### end Alembic commands ###
