"""empty message

Revision ID: b3055cee9d0e
Revises: 906904c2bfb9
Create Date: 2022-01-14 17:45:38.785572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3055cee9d0e'
down_revision = '906904c2bfb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('latitude', sa.Float(precision=20), nullable=False))
    op.drop_column('city', 'latitu')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('latitu', sa.REAL(), autoincrement=False, nullable=False))
    op.drop_column('city', 'latitude')
    # ### end Alembic commands ###
